@accountUrl = http://localhost:8080/account
@authenticationUrl = http://localhost:8080/auth
@id = {{create_account.response.body.id}}

# @name create_account
POST {{authenticationUrl}}/register
Content-Type: application/json

{
    "firstName": "Adrian",
    "lastName": "Almeida",
    "brideGroom": "AdrianAdria",
    "weddingDate": "2023-12-25",
    "email": "adrian1234@gmail.com",
    "password": "123456789",
    "pixKey": "071311121231"
}

###

POST {{authenticationUrl}}/login
Content-Type: application/json

{
    "email": "adrian1234@gmail.com",
    "password": "123456789"
}