@accountUrl = http://localhost:8080/account
@authenticationUrl = http://localhost:8080/auth
@id = {{create_account.response.body.id}}
@id = {{begin.response.body.id}}
@token = {{create_account.response.body.token}}
@token = {{authenticated.response.body.token}}

# @name create_account
POST {{authenticationUrl}}/register
Content-Type: application/json

{
    "firstName": "Adrian",
    "lastName": "Almeida",
    "brideGroom": "AdrianAdria",
    "weddingDate": "2023-12-25",
    "email": "adrian1234@gmail.com",
    "password": "123456789",
    "pixKey": "071311121231"
}

###

#  @name authenticated
POST {{authenticationUrl}}/login
Content-Type: application/json

{
    "email": "adrian1234@gmail.com",
    "password": "123456789"
}

###

# @name begin
GET {{accountUrl}}/begin?brideGroom=AdrianAdria

###

GET {{accountUrl}}/account?id={{id}}

###

PUT {{accountUrl}}/update?id={{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "weddingDate": "2023-12-15"
}

###

DELETE {{accountUrl}}/delete?id={{id}}
Authorization: Bearer {{token}}