spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/wedding-gifts
        username: postgres
        password: password
    
    jpa:
        hibernate:
            ddl-auto: update

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB

api:
    ssl:
        trust-store-type: JKS
        trust-store: src/main/resources/keystores/wedding-truststore-all.jks

        cert-type: X.509
        cert-oauth: src/certificates/oauth/hm/oauth_hm_ext_Balanceador_2023.pem
        cert-api-pix: src/certificates/api-pix.bb.com.br.cer

    security:
        token:
            secret: ${JTW_SECRET:secret_default}

    payment:
        oauth:
            url: ${OATUH_URL:https://oauth.hm.bb.com.br/oauth/token}

        pix:
            url: ${BB_PIX_URL:https://api.hm.bb.com.br/pix/v2}
            developer-key: ${BB_DEVELOPER_KEY:93d733261d022cd3d4082365eade35ca}
            client-id: ${BB_CLIENT_ID:eyJpZCI6IjhiNGU5OGZlLWYzODItNDJlYy05ZjM5LWU3ZWIzNzVmMzUxOSIsImNvZGlnb1B1YmxpY2Fkb3IiOjAsImNvZGlnb1NvZnR3YXJlIjo3ODk3NSwic2VxdWVuY2lhbEluc3RhbGFjYW8iOjF9}
            client-secret: ${BB_CLIENT_SECRET:eyJpZCI6IjM4MDk5IiwiY29kaWdvUHVibGljYWRvciI6MCwiY29kaWdvU29mdHdhcmUiOjc4OTc1LCJzZXF1ZW5jaWFsSW5zdGFsYWNhbyI6MSwic2VxdWVuY2lhbENyZWRlbmNpYWwiOjEsImFtYmllbnRlIjoiaG9tb2xvZ2FjYW8iLCJpYXQiOjE2OTk4MjQ0MzYwMTN9}
            scope: cob.write cob.read cobv.write cobv.read pix.write pix.read webhook.write webhook.read payloadlocation.write payloadlocation.read


server:
    ssl:
        alias: wedding-key

        enabled: true
        key-store-type: PKCS12
        key-store: src/main/resources/keystores/wedding-keystore.p12
        key-store-password: wedding-pass
        
        protocol: TLS
        enabled-protocols: TLSv1.2